### ISSUE TITLE
Does inline mode work?

### ISSUE THREAD

**Issue by taratandel** [Jeonhui/FittedSheets-SwiftUI#2]
I tried to implement the inline mode for like FittedSheet original library but it does not work

**Comment by Jeonhui** [comment]
I’ll check this soon. and i reply on this issue. 
thx. :)

**Comment by Jeonhui** [comment]
I updated inline mode in FittedSheets-SwiftUI v1.1.1 and finished testing. Can you leave an issue again if you have any problems after trying it?
