### ISSUE TITLE
Sheet Height Change

### ISSUE THREAD

**Issue by metallica1375** [Jeonhui/FittedSheets-SwiftUI#3]
Hey, When the height of content of the sheet changes, the sheet's height won't change. Imagine That I have a segmented button in my sheet that handles 3 different pages that shows in the sheet and the height of those pages differs. in this situation I have problem with auto increase or decrease the height of the sheet

**Comment by Jeonhui** [comment]
I will check this and fix it ASAP, thank you for notifying me know about this. 
Additionally, I will update Example App, after fix this issue. :)

**Comment by Jeonhui** [comment]
I fixed it like below.
I will distribute this version ASAP. Please wait some days. thx.
![Simulator Screen Recording - iPhone 15 Pro - 2024-05-18 at 21 55 47](https://github.com/Jeonhui/FittedSheets-SwiftUI/assets/48307153/7ff525eb-543b-445c-875c-1bf7f3c97ff6)

**Comment by Jeonhui** [comment]
I fixed this issue and distributed v1.2.0, can you check it?🙃

**Comment by metallica1375** [comment]
Thanks buddy! I'ma check it soon

**Comment by metallica1375** [comment]
I tested it and it worked just fine, thanks man. is there any option to prevent the sheet's root page to collapse a bit?
I want to have the inline mode behavior in the non-inline content

**Comment by Jeonhui** [comment]
Thx bro. Can i check the detailed code?

**Comment by pensacola1989** [comment]
can I remove the little pull bar？

**Comment by pensacola1989** [comment]
> can I remove the little pull bar？

just set the height to zero？

**Comment by Jeonhui** [comment]
@pensacola1989 
If you set the option to .init(pullBarHeight: .zero), you can see the image below.
<img width="200" alt="스크린샷 2024-06-10 00 35 27" src="https://github.com/Jeonhui/FittedSheets-SwiftUI/assets/48307153/d10ad9af-9532-4aa8-81a3-b71239891faa">

This library is depended on [FittedSheets](https://github.com/gordontucker/FittedSheets) and has implemented almost all of the features of FittedSheets for use in SwiftUI.
So I can't fix the UIViewController on FittedSheets. But I'll implement the Hide Pull Bar option if you need it or want it. (This code will not be much different from setting to pullBarHeight zero)

**Comment by pensacola1989** [comment]
thx



发自我的iPhone


------------------ Original ------------------
From: Jeonhui Lee ***@***.***&gt;
Date: Sun, Jun 9, 2024 11:46 PM
To: Jeonhui/FittedSheets-SwiftUI ***@***.***&gt;
Cc: ddw ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Jeonhui/FittedSheets-SwiftUI] Sheet Height Change (Issue #3)

**Comment by pensacola1989** [comment]
there is another issue that the container which hold the whole sreen in back is not round corner。any way to make it round？



发自我的iPhone


------------------ Original ------------------
From: Jeonhui Lee ***@***.***&gt;
Date: Sun, Jun 9, 2024 11:46 PM
To: Jeonhui/FittedSheets-SwiftUI ***@***.***&gt;
Cc: ddw ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Jeonhui/FittedSheets-SwiftUI] Sheet Height Change (Issue #3)

**Comment by pensacola1989** [comment]
<img width="393" alt="image" src="https://github.com/Jeonhui/FittedSheets-SwiftUI/assets/485505/c061eb5a-fe9a-4ec4-8357-a09abc869fd7">
I download FiteedSheet demo,it has rounded corner in background,and your wrapper of SwiftUI,screen shot blew:
<img width="155" alt="image" src="https://github.com/Jeonhui/FittedSheets-SwiftUI/assets/485505/1ee3ef3e-81eb-4c37-a625-176dfe068712">
